[package]
name = "random-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }

[build-dependencies]
cc = "1.0.79"
pkg-config = "0.3.16"
